name: Publish Python Package to PyPI

on:
  release:
    types: [published] # Trigger on new GitHub releases
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab

jobs:
  pypi-publish:
    name: Publish distributions to PyPI
    runs-on: ubuntu-22.04

    # REQUIRED for OIDC authentication with PyPI
    permissions:
      id-token: write # Grants permission to fetch the OIDC token
      contents: read  # Allows checking out your repository code

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.7'
          cache: 'pip'

      - name: Install build tool
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build source distribution and wheel
        run: python -m build --sdist --wheel --outdir dist/ .

      - name: Publish package to PyPI (via OIDC)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # No 'user' or 'password' needed for OIDC; the action automatically uses the token
          verbose: true
          # attestations: true # Uncomment this line if you want to enable PyPI attestations (recommended for supply chain security)
