name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read  # enough, no id-token needed

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install build tool
        run: |
          python -m pip install --upgrade build

      - name: Build release distributions
        run: |
          python -m build
          ls dist  # confirm dist folder was created

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist  # no slash!

  pypi-publish:
    runs-on: ubuntu-latest
    needs: release-build

    permissions:
      contents: read  # no id-token here

    environment:
      name: pypi

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
