name: Publish Python Package to PyPI

on:
  release:
    types: [published] # Trigger on new GitHub releases
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab

jobs:
  pypi-publish:
    name: Publish distributions to PyPI
    runs-on: ubuntu-22.04

    # IMPORTANT: Permissions for OIDC are TEMPORARILY REMOVED for API token upload.
    # You will re-add this block later for OIDC.
    # permissions:
    #   id-token: write
    #   contents: read

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.7'
          cache: 'pip'

      - name: Install build tool
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build source distribution and wheel
        run: python -m build --sdist --wheel --outdir dist/ .

      - name: Publish package to PyPI (Initial Upload with Token)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__ # Required for API token authentication
          password: ${{ secrets.PYPI_API_TOKEN }} # Uses the GitHub Secret you created
          verbose: true
          # attestations: true # Keep commented for initial upload
