name: Publish Python Package to PyPI !

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  pypi-publish:
    name: Publish distributions to PyPI
    runs-on: ubuntu-22.04

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.7'
          cache: 'pip'

      - name: Install build tool
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build source distribution and wheel
        run: python -m build --sdist --wheel --outdir dist/ .

      - name: Publish package to PyPI
        # CHANGE THIS LINE: Update to a newer version
        uses: pypa/gh-action-pypi-publish@v1.10.0 # <--- Changed from v1.9.0
        with:
          project_name: DiscordiaPy
